---
title: "CTEB-Lesson 1"
output:
  html_document:
    df_print: paged
---

# Fluctuation experiment (1943)
## First step
```{r}
#variables:
mutrate=1e-9   #mutation rate
w=1            #fitness of mutant
Nini=1000      #initial population
gen=20         #number of generations

#Assigments
x<-matrix(0,1,2)    #population matrix (1=wildtype (no mutation), 2 = mutant)
x[1,1]<-Nini

#Loop to simulate a population's growth and mutation over generations

for(g in 1:gen){
    x[1,1]<-x[1,1]*2            #growh rate of wildtipe is 2 (next generations)
    x[1,2]<-x[1,2]*2*w          #growth rate of mutant is 2w
    mutration<-rpois(1, mutrate*x[1,1])   #rpois: generacion de numeros pseudo aleatorios en la distribución de Poisson. 
                                          #1= numero de observacions a ser generadas
                                          #mutrate*x[1,1]=lambda (media o vector de medias)
    x[1,1]<-x[1,1]-mutration    #update matrix
    x[1,2]<-x[1,2]+mutration

#Observations
  #Sabemos que: x[0,0]=x[1,0]+x[1,1] y que x[0,1]=z[0,0]*2-x[1,1]
  #Es decir: 2000 0
  #          3999 1
    
    #print(c(g,x))    #show results
}

```
## Second step

````{r}
#variables:
mutrate=1e-9      #mutation rate
w=1               #fitness of mutant
Nini=1000         #initial population
gen=20            #number of generations
replicates =5000  #number of simulations (experiments)

data<-matrix(0,replicates,1) #container to store utput from each simulation

for(r in 1:replicates){

#Assigments
x<-matrix(0,1,2)    
x[1,1]<-Nini


  for(g in 1:gen){
      x[1,1]<-x[1,1]*2           
      x[1,2]<-x[1,2]*2*w
      
      mutration<-rpois(1, mutrate*x[1,1])   
      
      x[1,1]<-x[1,1]-mutration    #update matrix
      x[1,2]<-x[1,2]+mutration
      
      #print(c(g,x))    #show results
  }
  data[r]<-x[1,2]/sum(x)
}
hist(log10(data), breaks=50, col='#8da0cb', ylim=c(0,1000), xlim=c(-9, -3))
````